version: "3.7"

services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    networks:
      - proxy_net
    environment:
      - KASM_PORT=8443
      #- DOCKER_HUB_USERNAME=USER #optional
      #- DOCKER_HUB_PASSWORD=PASS #optional
    volumes:
      - ./kasm/data:/opt
      - ./kasm/profiles:/profiles #optional
      - /dev/input:/dev/input #optional
      - /run/udev/data:/run/udev/data #optional
    ports:
      - 3000:3000
      - 8443:8443
    restart: unless-stopped
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    networks:
      - proxy_net
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config

networks:
  proxy_net:
